version: "3.8"

networks:
  kafka_network:
    driver: bridge

services:
  kafka1:
    image: bitnami/kafka:3.5.1-debian-11-r0
    container_name: kafka1
    platform: linux/arm64
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - ${DATA_DIR:-./data}/kafka1:/bitnami/kafka
    networks:
      - kafka_network

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    platform: linux/arm64
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka_local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:9092
    depends_on:
      - kafka1
    networks:
      - kafka_network
